### ISSUE TITLE
GET https://login.coinbase.com/oauth2/auth?response_type=code&client_id=YOUR_CLIENT_ID&redirect_uri=YOUR_REDIRECT_URL&state=SECURE_RANDOM&scope=wallet:accounts:read

### ISSUE THREAD

**Issue by billygonz69** [goauthentik/authentik#10122]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

```[tasklist]
### Tasks
- [ ] https://github.com/goauthentik/authentik/issues/9581
- [ ] https://github.com/goauthentik/authentik/issues/10463
- [ ] https://github.com/goauthentik/authentik/pull/10460
```
