### ISSUE TITLE
Redis TLS Connection

### ISSUE THREAD

**Issue by michael-pisman** [goauthentik/authentik#12041]
## Description
My **Redis** server requires client TLS certificates. As of now the **authentik** and helm chart support CA certificate but I also need to include private key and certificate.

In addition, according to redis python library docs,  `ssl_certfile` and `ssl_keyfile` should be included -  [link](https://redis-py.readthedocs.io/en/stable/examples/ssl_connection_examples.html) 

**Error from logs:**

```
Error while reading from authentik-redis-master.authentik.svc.cluster.local:6379:(1,'[SSL:TLSV13_ALERT_CERTIFICATE_REQUIRED] tlsv13 alert certificate required (_ssl.c:2559)')
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.3
-   Deployment: Kubernetes helm chart

## Additional context

I created a simple script to test if the lack of key and certificate would cause the same error and it does.

```python
import redis
import pprint

try:
  redis_url = "rediss://:password@127.0.0.1:6379?ssl_cert_reqs=required&ssl_ca_certs=./ca.crt"
  r = redis.StrictRedis.from_url(redis_url, decode_responses=True)

  info = r.info()
  pprint.pprint(info)

except Exception as err:
  print("Error connecting to Redis: {}".format(err)) 
```

The above gives me the same error:

```
Error connecting to Redis: Error while reading from 127.0.0.1:6381 : (1, '[SSL: TLSV13_ALERT_CERTIFICATE_REQUIRED] tlsv13 alert certificate required (_ssl.c:2591)')
```

However, if I add the missing files, everything will work

```python
import redis
import pprint

try:
   redis_url = "rediss://:password@127.0.0.1:6379?ssl_cert_reqs=required&ssl_keyfile=./tls.key&ssl_certfile=./tls.crt&ssl_ca_certs=./ca.crt"
   r = redis.StrictRedis.from_url(redis_url, decode_responses=True)

  info = r.info()
  pprint.pprint(info)

except Exception as err:
  print("Error connecting to Redis: {}".format(err)) 
```

## Proposed Resolution

If I am correct, [config.py](https://github.com/goauthentik/authentik/blob/main/authentik/lib/config.py) file needs fixing and also helm chart.

https://github.com/goauthentik/authentik/blob/6702f34b40900e4c8fc6f538da3a6b927ed9faee/authentik/lib/config.py#L319-L336

If you approve, I can try to work on this over the weekend.
```[tasklist]
### Tasks
- [ ] Add `AUTHENTIK_REDIS__TLS_KEY` and `AUTHENTIK_REDIS__TLS_CERT` to helm chart
- [ ] Add `TLS_KEY` and `TLS_CERT` to configs
- [ ] Update `redis_url()` in `config.py` to include `ssl_keyfile` and `ssl_certfile`
```

---

## Workaround

The simplest workaround I could think of is to add required TLS files into query string. Since `AUTHENTIK_REDIS__TLS_CA_CERT` variable is only used for concatenation of the Redis url, simply add  `ssl_keyfile` `ssl_certfile` after the `ca_certs` file, and point them to the mounted secrets.

```yaml
- name: AUTHENTIK_REDIS__TLS_CA_CERT
  value: "/secrets/redis-tls/ca.crt&ssl_keyfile=/secrets/redis-tls/tls.key&ssl_certfile=/secrets/redis-tls/tls.crt"
```

This is an example for helm chart to deploy Authentik to Kubernetes. Update your `values.yaml` accordingly(this is not a valid nor full config)

```yaml

global:
  env:
    # Redis config
    - name: AUTHENTIK_REDIS__HOST
      value: "redis.authentik.svc.cluster.local"
    - name: AUTHENTIK_REDIS__PASSWORD
      valueFrom:
        secretKeyRef:
          name: redis-password
          key: redis-password
    - name: AUTHENTIK_REDIS__TLS
      value: "True"
    - name: AUTHENTIK_REDIS__TLS_REQS
      value: "required"
    - name: AUTHENTIK_REDIS__TLS_CA_CERT
      value: "/secrets/redis-tls/ca.crt&ssl_keyfile=/secrets/redis-tls/tls.key&ssl_certfile=/secrets/redis-tls/tls.crt"

  # Mount tls secrets to /secrets
  volumes:
    - name: redis-tls
      secret:
        secretName: redis-tls
        defaultMode: 0644
        items:
          - key: tls.key
            path: tls.key
          - key: tls.crt
            path: tls.crt
          - key: ca.crt
            path: ca.crt

  volumeMounts:
    - name: redis-tls
      mountPath: "/secrets/redis-tls"
      readOnly: true
  
  # Update securityContext so pod can access the mounted secrets
  securityContext:
    runAsUser: 1000     # UID of authentik user
    runAsGroup: 1000    # GID of authentik user
    fsGroup: 1000
```

Using this approach, I was able to deploy Authentik.

**Comment by mike-pisman** [comment]
### A little update:
First of all, I forgot to mention that I tried combining 3 certificates into one pem file, but that does not work.

Second, although my workaround works for **Authentik server** itself, it does **not** work for parts of authentik written in **GO** like _outposts_ for example. **Authentik server** uses python to connect to **Redis**, outposts, on the other hand, are written in **GO Lang**, which complicates things even worse. While **Authentik server** simply append the contents of the TLS Config to connection URL, outposts actually load the file from the path specified in the config, which causes an error that file "/secrets/redis-tls/ca.crt&ssl_keyfile=/secrets/redis-tls/tls.key&ssl_certfile=/secrets/redis-tls/tls.crt" does not exist for obvious reasons.

https://github.com/goauthentik/authentik/blob/4b5e66f9eb2c5e932239eb81e7f07ea1ff1b72d4/internal/outpost/proxyv2/application/session.go#L47-L62

**Comment by mike-pisman** [comment]
### A little update:
First of all, I forgot to mention that I tried combining 3 certificates into one pem file, but that does not work.

Second, although my workaround works for **Authentik server** itself, it does **not** work for parts of authentik written in **GO** like _outposts_ for example. **Authentik server** uses python to connect to **Redis**, outposts, on the other hand, are written in **GO Lang**, which complicates things even worse. While **Authentik server** simply append the contents of the TLS Config to connection URL, outposts actually load the file from the path specified in the config, which causes an error that file "/secrets/redis-tls/ca.crt&ssl_keyfile=/secrets/redis-tls/tls.key&ssl_certfile=/secrets/redis-tls/tls.crt" does not exist for obvious reasons.

https://github.com/goauthentik/authentik/blob/4b5e66f9eb2c5e932239eb81e7f07ea1ff1b72d4/internal/outpost/proxyv2/application/session.go#L47-L62

**Comment by rissson** [comment]
FYI we're sloooooowly moving away from Redis, so this probably won't get much attention from us.

**Comment by dimm0** [comment]
To what?

**Comment by rissson** [comment]
Only using postgres
